#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT_DIR}/.env.dev.local"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.dev.yml"
PROJECT_NAME="sequoia-map-mod-ingest"
PGDATA_VOLUME="${PROJECT_NAME}_pgdata-dev"

random_hex() {
  local bytes="${1}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${bytes}"
    return
  fi

  python3 - "${bytes}" <<'PY'
import secrets
import sys

print(secrets.token_hex(int(sys.argv[1])))
PY
}

port_in_use() {
  local port="${1}"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "( sport = :${port} )" | tail -n +2 | grep -q .
    return
  fi

  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"${port}" -sTCP:LISTEN -t >/dev/null 2>&1
    return
  fi

  return 1
}

select_postgres_port() {
  local candidate
  for candidate in $(seq 55432 55464); do
    if ! port_in_use "${candidate}"; then
      printf '%s\n' "${candidate}"
      return
    fi
  done

  echo "Unable to find a free local Postgres port in the 55432-55464 range." >&2
  exit 1
}

find_service_container() {
  local service="${1}"
  docker ps -a \
    --filter "label=com.docker.compose.project=${PROJECT_NAME}" \
    --filter "label=com.docker.compose.service=${service}" \
    --format '{{.Names}}' \
    | head -n1
}

read_container_env() {
  local container="${1}"
  local key="${2}"

  docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "${container}" \
    | sed -n "s/^${key}=//p" \
    | tail -n1
}

read_postgres_port_from_container() {
  local container="${1}"

  docker port "${container}" 5432/tcp \
    | awk -F: 'NR == 1 { print $NF }'
}

write_env_file() {
  local postgres_password="${1}"
  local internal_ingest_token="${2}"
  local postgres_port="${3}"
  local note="${4}"

  umask 077
  cat >"${ENV_FILE}" <<EOF
# ${note}
POSTGRES_PASSWORD=${postgres_password}
INTERNAL_INGEST_TOKEN=${internal_ingest_token}
POSTGRES_PORT=${postgres_port}
EOF
}

recover_env_file_from_existing_stack() {
  local postgres_container
  local server_container
  local ingest_container
  local postgres_password
  local internal_ingest_token
  local postgres_port

  postgres_container="$(find_service_container postgres)"
  server_container="$(find_service_container server)"
  ingest_container="$(find_service_container ingest)"

  if [[ -z "${postgres_container}" ]]; then
    return 1
  fi

  postgres_password="$(read_container_env "${postgres_container}" POSTGRES_PASSWORD)"
  postgres_port="$(read_postgres_port_from_container "${postgres_container}")"

  if [[ -n "${server_container}" ]]; then
    internal_ingest_token="$(read_container_env "${server_container}" INTERNAL_INGEST_TOKEN)"
  fi
  if [[ -z "${internal_ingest_token:-}" && -n "${ingest_container}" ]]; then
    internal_ingest_token="$(read_container_env "${ingest_container}" SEQUOIA_INTERNAL_INGEST_TOKEN)"
  fi

  if [[ -z "${postgres_password}" || -z "${internal_ingest_token:-}" || -z "${postgres_port}" ]]; then
    return 1
  fi

  write_env_file \
    "${postgres_password}" \
    "${internal_ingest_token}" \
    "${postgres_port}" \
    "Generated by ./dev.sh from the existing ${PROJECT_NAME} Docker stack. Safe to edit."
  echo "Created ${ENV_FILE} from the existing ${PROJECT_NAME} Docker stack."
  return 0
}

ensure_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    return
  fi

  if recover_env_file_from_existing_stack; then
    return
  fi

  if docker volume inspect "${PGDATA_VOLUME}" >/dev/null 2>&1; then
    cat >&2 <<EOF
Found existing Docker volume ${PGDATA_VOLUME} but could not recover the dev credentials for it.
Either remove that volume if you do not need the local database anymore, or create ${ENV_FILE}
manually with matching POSTGRES_PASSWORD, INTERNAL_INGEST_TOKEN, and POSTGRES_PORT values.
EOF
    exit 1
  fi

  local postgres_port
  postgres_port="$(select_postgres_port)"

  write_env_file \
    "$(random_hex 24)" \
    "$(random_hex 24)" \
    "${postgres_port}" \
    "Generated by ./dev.sh. Safe to edit for local development."

  echo "Created ${ENV_FILE} with stable dev credentials and POSTGRES_PORT=${postgres_port}."
}

main() {
  local compose_args=("$@")

  if [[ ${#compose_args[@]} -eq 0 ]]; then
    compose_args=(up --build)
  fi

  ensure_env_file

  exec docker compose \
    --project-name "${PROJECT_NAME}" \
    --env-file "${ENV_FILE}" \
    -f "${COMPOSE_FILE}" \
    "${compose_args[@]}"
}

main "$@"
